---
  - hosts: all
    tasks: []

  - hosts: localhost
    connection: local
    tasks:
      - name: Create already_configured Group
        add_host:
          groups: already_configured
          name: "{{ item }}"
        with_items: "{{ groups['raspberries'] }}"
        when: hostvars[item]['hostname'] | regex_search('(.*)(-\d)')

      - set_fact:
          id_max: "{{ groups['already_configured'] | length }}"

      - name: Createe First Time Setup Group
        add_host:
          groups: first_time_setup
          name: "{{ item }}"
          target_hostname: "cluster-pi-{{ id_max | int + index | int }}.cdf.ndavies.io"
        loop: "{{ groups['raspberries'] | difference(groups['already_configured']) }}"
        loop_control:
          index_var: index
        when: hostvars[item]['hostname'] == 'raspberrypi'

  - hosts: first_time_setup
    become: true
    tasks:
      - debug:
          msg: "{{ target_hostname }}"
      
      - name: Set Hostname
        hostname:
          name: "{{ target_hostname }}"
      
      - name: Reboot
        reboot: