#
# Basic configuration playbook for raspberry pi.
#

- hosts: all
  become: true
  tasks:
    - name: Install common packages
      apt:
        name: "{{ item }}"
        state: present
      with_items:
        - git
        - vim
        